### PR TITLE
1.16 Update & Maven Conversion

### PR DESCRIPTION
**Pull request by MrKorvic**
Add NMS 1.16 to keep the plugin functional without errors on 1.16. Everything else seemingly still functions. In order to import things properly the project has been converted to a Maven project to help keep things easy to maintain in the future. If you're more of a Gradle fan feel free to use `gradle init` to convert it over. Thanks for the great work on the plugin, hopefully this helps you out with keeping it updated!

Happy armour standing!
**Korvic**
_[https://www.lostfables.net](url)_

### CODE REVIEW

**Comment by MrKorvic** [comment]
Added 1.16.2 NMS (`bv` for those with their own forks).

**Comment by stijnb1234** [comment]
>>> >.... [13:19:53 WARN]: java.lang.NoSuchFieldException: bv
>.... [13:19:53 WARN]: at java.lang.Class.getDeclaredField(Class.java:2070)
>.... [13:19:53 WARN]: at com.gmail.St3venAU.plugins.ArmorStandTools.NMS.setSlotsDisabled(NMS.java:90)
>.... [13:19:53 WARN]: at com.gmail.St3venAU.plugins.ArmorStandTools.MainListener.spawnArmorStand(MainListener.java:420)
>.... [13:19:53 WARN]: at com.gmail.St3venAU.plugins.ArmorStandTools.MainListener.onPlayerInteract(MainListener.java:355)
>.... [13:19:53 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor514.execute(Unknown Source)
>.... [13:19:53 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [13:19:53 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [13:19:53 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [13:19:53 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [13:19:53 WARN]: at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1535)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
>.... [13:19:53 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [13:19:53 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by MrKorvic** [comment]
Haven't done a 1.16.3 or 1.16.4 update to it, been caught up with other things. Your error is telling you that the NMS code being used is wrong due to the version change, so you'll have to wait or see about changing it yourself for the time being. To find out what it would need to be changed to you'd have to run build tools and check the values for 1.16.3 & 1.16.4 compared to previous versions.

**Comment by stijnb1234** [comment]
Created a PR to add that.

https://github.com/Lost-Fables/ArmorStandTools/pull/1

**Comment by stijnb1234** [comment]
Just a note. 1_16R4 doesn't exists.

1.16.1 was 1_16R1
1.16.2 and 1.16.3 are 1_16R2
1.16.4 is 1_16R3

**Review by St3venAU — APPROVED** [review]

**Comment by MrKorvic** [comment]
Mojang is quite wacky sometimes... I'll throw up a change to that sometime tomorrow morning most likely after double-checking the build tools output. Just got off a 12-hour shift and am a bit beat haha @stijnb1234

**Pull request merged**
